### PR TITLE
Add delay

### PR DESCRIPTION
**Pull request by decates**
Add customisable delay (milliseconds) (Feat request #8 ) to support routing transitions.

### CODE REVIEW

**Comment by decates** [comment]
I'm aware that introducing setTimeout(..., 0) as a default modifies existing behaviour slightly, but don't envisage this being a problem.

**Comment by jeneser** [comment]
Yep, if we use `setTimeout(..., 0)`, we may not be sure what's going to happen. 
And, How long is the delay? Not just the transitions, there may be some delayed Ajax. Too long or too short will affect the user experience.

**Comment by decates** [comment]
Changed to avoid setTimeout when there is no delay specified. I was expecting this PR/feature to just be about allowing users to specify a fixed delay. It feels like handling ajax is a different (and useful) feature.

**Comment by jeneser** [comment]
Good job! Let me test it.

**Pull request merged**
